### ISSUE TITLE
Can LongDat handle nested effects?

### ISSUE THREAD

**Issue by carmennns2** [CCY-dev/LongDat#2]
Hello, 

Thank you for the tool!

Can longdat_cont handle nested effects? For example, I have samples from 7 individuals (Individuals). Each individual can produce multiple donations (Sample_donation). Some individuals produce 5 donations, some only donate 1. Each donation is assessed across time (months). The time the samples are assessed is not consistent. Some samples are measured at months 0, 6, 12, 18, some at 1,5,10, 12, at, etc. Each sample at each timepoint have their own unique label (sample_label).

For my master table, I am using this:
`master <- make_master_table(metadata_table = metadata,
                                    feature_table = feature, sample_ID = "sample_label", individual = (Sample_donation))
`

To run LongDat, I am using this:
`test_cont <- longdat_cont(input = master, data_type = "count", test_var = "Time", variable_col = 5, fac_var = c(1:5), adjustMethod = "BH", model_q = 0.05) `

However, these codes only take into account the effect of time in each Sample_donation. Is there a way I can assess the effect of time in each Sample_donation of each Individual?

Thank you so much (:

Wishing you a great 2024!

**Comment by CCY-dev** [comment]
Hi, 

Thank you for the question. If I understand you correctly, your data looks like this: 
![Screenshot 2024-01-06 at 12 44 03](https://github.com/CCY-dev/LongDat/assets/70947767/8466a0f9-d3db-4ee9-a87b-6862ad8bb948)
Is this correct? 

If you'd like to assess the time effect on each individual, you could take the Individual column as an individual argument, and the Sample_donation as sample_ID when executing the make_master_table function. For example:

`test_master <- make_master_table(
metadata_table = meta_table,
feature_table = feature_table,
sample_ID = "Sample_ID",
individual = "Individual")`

Next, when running longdat_cont(), remove or ignore (using the not_used argument) your Sample_donation column, as it is only useful when merging meta and feature tables, but doesn't make sense to be included as a covariate. Longdat_cont() is designed for cases like yours when the sampling time points aren't uniform across individuals. Longdat_cont() will test the effect of time on the feature variables, using Individual as the random (nested) variable. 

I hope this helps!

**Comment by carmennns2** [comment]
Thank you @CCY-dev for the quick response (:

You are mostly correct about the metadata. It looks more like this, where not only are the months inconsitent, however, also the number of donations per individual. 
![image](https://github.com/CCY-dev/LongDat/assets/81758375/d46f6549-1faf-4323-ae8d-e94b8aff36a7)

However, if I were to set "Sample_ID = "Sample_donation"  instead of "Sample_label" to assess the time effect on each individual, I would no longer be able to assess the time effect within each donation. Is this correct? 

Thank you so much for your explanation!

**Comment by CCY-dev** [comment]
Thanks for providing an example of your data. Longdat_cont can handle a different number of donations per individual.

If you're interested in the time effect within each donation, you could divide the data into different donations, and run longdat_cont on each donation one by one. In this case, you can assess the time effect within each individual donation, and compare the results across donations if this is what you want.

I hope this helps!

**Comment by carmennns2** [comment]
That is the answer I am looking for!

Thank you (:

All the best.
